name: Metrics

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          user: ValneiPereira
          template: classic

          # Base limpa
          base: repositories
          config_timezone: America/Sao_Paulo

          # Plugin: Languages (forma correta)
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_limit: 6
          plugin_languages_threshold: 2%
          plugin_languages_categories: backend, frontend
          plugin_languages_colors: github
          plugin_languages_ignored: html, css
