name: Metrics

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          user: ValneiPereira
          template: classic

          # Base limpa (sem contadores sociais)
          #base: repositories

          # Mostra linguagens (backend-focused)
          languages: yes
          languages_details: percentage
          languages_limit: 6
          languages_threshold: 2%
          languages_categories: backend, frontend
          languages_colors: github

          # Ignora ru√≠do comum
          languages_ignored: html, css

          # Timezone correta
          config_timezone: America/Sao_Paulo
